"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GalleryController = exports.DownloadController = exports.DashboardController = exports.RegistrationController = exports.GeneralSettingController = exports.EventGalleryController = exports.EventController = exports.BabySizeController = exports.SubscribeController = exports.EnquiryController = exports.PartnerController = exports.CommunityController = exports.CommunityCategoryController = exports.DiaryController = exports.FaqController = exports.TestimonialController = exports.AdminController = void 0;
const AdminController_1 = __importDefault(require("./AdminController"));
exports.AdminController = AdminController_1.default;
const TestimonialController_1 = __importDefault(require("./TestimonialController"));
exports.TestimonialController = TestimonialController_1.default;
const FaqController_1 = __importDefault(require("./FaqController"));
exports.FaqController = FaqController_1.default;
const DiaryController_1 = __importDefault(require("./DiaryController"));
exports.DiaryController = DiaryController_1.default;
const CommunityCategoryController_1 = __importDefault(require("./CommunityCategoryController"));
exports.CommunityCategoryController = CommunityCategoryController_1.default;
const CommunityController_1 = __importDefault(require("./CommunityController"));
exports.CommunityController = CommunityController_1.default;
const PartnerController_1 = __importDefault(require("./PartnerController"));
exports.PartnerController = PartnerController_1.default;
const EnquiryController_1 = __importDefault(require("./EnquiryController"));
exports.EnquiryController = EnquiryController_1.default;
const SubscribeController_1 = __importDefault(require("./SubscribeController"));
exports.SubscribeController = SubscribeController_1.default;
const BabySizeController_1 = __importDefault(require("./BabySizeController"));
exports.BabySizeController = BabySizeController_1.default;
const EventController_1 = __importDefault(require("./EventController"));
exports.EventController = EventController_1.default;
const EventGalleryController_1 = __importDefault(require("./EventGalleryController"));
exports.EventGalleryController = EventGalleryController_1.default;
const GeneralSettingController_1 = __importDefault(require("./GeneralSettingController"));
exports.GeneralSettingController = GeneralSettingController_1.default;
const RegistrationController_1 = __importDefault(require("./RegistrationController"));
exports.RegistrationController = RegistrationController_1.default;
const DashboardController_1 = __importDefault(require("./DashboardController"));
exports.DashboardController = DashboardController_1.default;
const DownloadController_1 = __importDefault(require("./DownloadController"));
exports.DownloadController = DownloadController_1.default;
const GalleryController_1 = __importDefault(require("./GalleryController"));
exports.GalleryController = GalleryController_1.default;
//# sourceMappingURL=index.js.map