"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.GalleryService = exports.DownloadService = exports.RegistrationService = exports.GeneralSettingService = exports.EventGalleryService = exports.EventService = exports.BabySizeService = exports.SubscribeService = exports.EnquiryService = exports.CommunityService = exports.CommunityCategoryService = exports.PartnerService = exports.DiaryService = exports.FaqService = exports.TestimonialService = exports.AdminService = void 0;
const AdminService_1 = __importDefault(require("./AdminService"));
exports.AdminService = AdminService_1.default;
const TestimonialService_1 = __importDefault(require("./TestimonialService"));
exports.TestimonialService = TestimonialService_1.default;
const FaqService_1 = __importDefault(require("./FaqService"));
exports.FaqService = FaqService_1.default;
const DiaryService_1 = __importDefault(require("./DiaryService"));
exports.DiaryService = DiaryService_1.default;
const CommunityCategoryService_1 = __importDefault(require("./CommunityCategoryService"));
exports.CommunityCategoryService = CommunityCategoryService_1.default;
const CommunityService_1 = __importDefault(require("./CommunityService"));
exports.CommunityService = CommunityService_1.default;
const PartnerService_1 = __importDefault(require("./PartnerService"));
exports.PartnerService = PartnerService_1.default;
const EnquiryService_1 = __importDefault(require("./EnquiryService"));
exports.EnquiryService = EnquiryService_1.default;
const SubscribeService_1 = __importDefault(require("./SubscribeService"));
exports.SubscribeService = SubscribeService_1.default;
const BabySizeService_1 = __importDefault(require("./BabySizeService"));
exports.BabySizeService = BabySizeService_1.default;
const EventService_1 = __importDefault(require("./EventService"));
exports.EventService = EventService_1.default;
const EventGalleryService_1 = __importDefault(require("./EventGalleryService"));
exports.EventGalleryService = EventGalleryService_1.default;
const GeneralSettingService_1 = __importDefault(require("./GeneralSettingService"));
exports.GeneralSettingService = GeneralSettingService_1.default;
const RegistrationService_1 = __importDefault(require("./RegistrationService"));
exports.RegistrationService = RegistrationService_1.default;
const DownloadService_1 = __importDefault(require("./DownloadService"));
exports.DownloadService = DownloadService_1.default;
const GalleryService_1 = __importDefault(require("./GalleryService"));
exports.GalleryService = GalleryService_1.default;
//# sourceMappingURL=index.js.map